import { Montserrat } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar/NavigationBar";
import Footer from "@/components/Footer/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight :  ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable : "var(--font-Montserrat)",
});

export const metadata = {
  title: "Portfolio 4 Sibusiso",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <NavigationBar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
